---
- name: Update Homebrew
  community.general.homebrew:
    path: "{{ macos_homebrew_path }}"
    update_homebrew: yes

- name: Install packages via Homebrew
  community.general.homebrew:
    name:
      - colima
      - docker
      - docker-compose
      - docker-credential-helper
      - gh
      - ghq
      - jq
      - fq
      - tree
      - tmux
      - neovim
      - shellcheck
      - nodenv
      - pnpm
    path: "{{ macos_homebrew_path }}"
    state: latest

- name: Install packages via Homebrew Cask
  community.general.homebrew_cask:
    name:
      - bitwarden
      - ghostty
      - google-chrome
      - slack
      - spotify
      - visual-studio-code
    path: "{{ macos_homebrew_path }}"
    state: latest
