name: Pop!_OS

on:
  push:
    workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: make ansible/init ansible/lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: init
        run: make popos/init bash/init ansible/init

      - name: test
        run: |
          source ~/.bashrc
          make ansible/test
        shell: bash {0}

  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: make ansible/init ansible/check
