name: Pop!_OS

on:
  push:
    workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: init
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          make popos/init bash/init

      - name: lint
        run: |
          source ~/.bashrc
          make ansible/init ansible/lint
        shell: bash {0}

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: init
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          make popos/init bash/init

      - name: test
        run: |
          source ~/.bashrc
          make ansible/init ansible/test
        shell: bash {0}

  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: init
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          make popos/init bash/init

      - name: check
        run: |
          source ~/.bashrc
          make ansible/init ansible/check
        shell: bash {0}
